darwinia:
  - config: daos/ring-dao.yml
    state: active
  - config: daos/kton-dao.yml
  - config: daos/ring-dao-guild.yml

  - config: daos/degov-no-timelock.yml
    tags:
      - demo
  - config: daos/degov-blocknumber.yml
    tags:
      - demo
  - config: https://demo.degov.ai/degov.yml
    domains:
      - demo.degov.ai
    tags:
      - demo

ethereum:
  - config: daos/ens-dao.yml
  # - config: daos/truefi-dao.yml
  - config: daos/fluence-dao.yml

base:
  - config: daos/aquari-dao.yml
    domains:
      - gov.aquari.org
  - config: daos/unlock-dao.yml
  - config: daos/carv-dao.yml
  - config: daos/awe-dao.yml
  - config: daos/internet-token-dao.yml
  - config: daos/lazy-summer.yml
  - config: daos/seamless-dao.yml
  - config: daos/aixbt-dao.yml

arbitrum:
  - config: daos/rn-dao.yml
  - config: daos/gmx-dao.yml

optimism:
  - config: daos/hai-dao.yml

lisk:
  - config: daos/lisk-dao.yml
